### ISSUE TITLE
Json array is transformed in map when removing empty elements

### ISSUE THREAD

**Issue by corinapurcarea** [adobe/athena#33]
### Expected Behaviour
Json array stays as array when removing empty elements

### Actual Behaviour
Json array is transformed in map when removing empty elements

#### Steps to Reproduce
Set examples/performance/perfRun.yaml to
```
name: "apiKey"
version: "1.0"
description: ""
engine: autocannon
type: perfRun
config:
  url: https://api-gateway-qe-d-ue1.adobe.io/test
  connections: 2000
  duration: 30
  method: GET
  requests: # Array of objects.
    - headers:
        host: keepalive-with-upstream-test-stage-service-1.adobe.io
      method:
      path:
    - headers:
        host: baseline-performance-testing-stage-service-1.adobe.io
hooks:
  onInit:
  onDestroy:
  onRequest:
```
and run athena
